[window]
opacity = 0.7
padding.x = 25
padding.y = 25

[colors]
transparent_background_colors = true
# background_opacity = 0.3 # Does not work currently in alacritty

[colors.primary]
foreground = "#e7aa5a"
background = "#1c0e00"

[colors.normal]
black   = "#72696a"
red     = "#fd6883"
green   = "#DF782D"
yellow  = "#f9cc6c"
blue    = "#66A891"
magenta = "#a8a9eb"
cyan    = "#BD4924"
white   = "#e6d9db"

[colors.bright]
black   = "#948a8b"
red     = "#ff8297"
green   = "#c8e292"
yellow  = "#fcd675"
blue    = "#f8a788"
magenta = "#bebffd"
cyan    = "#9bf1e1"
white   = "#f1e5e7"

[colors.cursor]
text   = "#e7aa5a"
cursor = "#e7aa5a"
